apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o komposed/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dstu2
  name: dstu2
spec:
  ports:
    - name: "8078"
      port: 8078
      targetPort: 8078
  selector:
    io.kompose.service: dstu2
status:
  loadBalancer: {}
