apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o komposed/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o komposed/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - -Djboss.http.port=8080
            - -Dkeycloak.profile.feature.upload_scripts=enabled
          env:
            - name: KEYCLOAK_IMPORT
              value: /etc/security/realm_properties.json
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KEYCLOAK_USER
              value: admin
          image: jboss/keycloak
          name: keycloak
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /etc/security
              name: security
      restartPolicy: Always
#      volumes:
#        - name: keycloak-claim0
#          persistentVolumeClaim:
#            claimName: keycloak-claim0
      volumes:
        - name: security
          hostPath:
            path: /etc/security
status: {}
