apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o komposed/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: patient-data-manager
  name: patient-data-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: patient-data-manager
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o komposed/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: patient-data-manager
    spec:
      containers:
        - image: logicahealth/patient-data-manager
          name: patient-data-manager
          ports:
            - containerPort: 8096
          resources: {}
      restartPolicy: Always
status: {}
