apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o komposed/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: r4
  name: r4
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: r4
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o komposed/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: r4
    spec:
      containers:
        - env:
            - name: API_PORT
              value: "8070"
            - name: AUTH_HOST
              value: sandbox
            - name: AUTH_PORT
              value: "8060"
            - name: DB_HOST
              value: sandbox-mysql
            - name: DB_PASSWORD
              value: password
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: MANIFEST_OVERRIDE
              value: "false"
            - name: SANDBOX_NAME
              value: hspc10
            - name: SBMA_HOST
              value: sandbox-manager-api
            - name: SBMA_PORT
              value: "12000"
            - name: SPRING_PROFILES_ACTIVE
              value: r4,multitenant
          image: logicahealth/api
          name: r4
          ports:
            - containerPort: 8070
          resources: {}
      restartPolicy: Always
status: {}
