apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o komposed/
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: r5
  name: r5
spec:
  ports:
    - name: "8071"
      port: 8071
      targetPort: 8071
  selector:
    io.kompose.service: r5
  type: LoadBalancer
  externalIPs:
    - 10.96.0.1
status:
  loadBalancer: {}
