apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o komposed/
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: sandbox
  name: sandbox
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "3001"
      port: 3001
      targetPort: 3001
    - name: "8060"
      port: 8060
      targetPort: 8060
  selector:
    io.kompose.service: sandbox
  type: LoadBalancer
  externalIPs:
    - 10.96.0.1
status:
  loadBalancer: {}
