apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o komposed/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: static-content
  name: static-content
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: static-content
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o komposed/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: static-content
    spec:
      containers:
        - image: logicahealth/sandbox-ce-static-content
          name: static-content
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
