apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o komposed/
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: static-content
  name: static-content
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 80
  selector:
    io.kompose.service: static-content
  type: LoadBalancer
  externalIPs:
    - 10.96.0.1
status:
  loadBalancer: {}
