apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o komposed/
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: stu3
  name: stu3
spec:
  ports:
    - name: "8079"
      port: 8079
      targetPort: 8079
  selector:
    io.kompose.service: stu3
  type: LoadBalancer
  externalIPs:
    - 10.96.0.1
status:
  loadBalancer: {}
